    spring:
      config:
        activate:
          on-profile: prod
      datasource:
        url: jdbc:mysql://localhost:3306/sparta_example
        username: root
        password: 56781234
    jwt:
      secret:
        key: g9kszkHTlGSJRtfAUkq8i7d/7+gDayMy0gCEmZS0zOhehRTPyALLoDMCVTwIOpLNl7X7jZLir/vN1PDsU51Ixg==